### ISSUE TITLE
Cloudflare worker should not have underscores in the name

### ISSUE THREAD

**Issue by brettflorio** [Foxy/foxy-cloudflare-membership-site#1]
Apparently Cloudflare allows underscores in domain names that are used in the Worker URLs, which is weird and can cause problems. We should update the `.toml` file to prevent this by default. It seems like this might prevent things from working, by default.

https://community.cloudflare.com/t/cloudflare-workers-published-on-workers-dev-unreachable-error-523-to-error-522/130014

**Comment by ndvo** [comment]
This issue should have been closed by c2d6abb3dcda2dd88d9ade84d6c83263a8014da5
